### PR TITLE
Append access token by interceptor

### PR DESCRIPTION
**Pull request by alvince**

### CODE REVIEW

**Comment by yellowbluesky** [comment]
I'll review and merge later tonight when I'm off work

Thanks for your work in improving this app :)

**Comment by yellowbluesky** [comment]
Do you mind if I credit you in this repos readme and in the app? If yes, let me know if linking to your Github is alright with you, or if you want me to link to anywhere else

**Comment by alvince** [comment]
> Do you mind if I credit you in this repos readme and in the app? If yes, let me know if linking to your Github is alright with you, or if you want me to link to anywhere else

Thx, I am glad about that

**Comment by yellowbluesky** [comment]
No worries :)

Also, please let me know if there's anything I am doing wrong or if I can improve, you seem like a much more knowledgeable Android developer than me

**Pull request merged**
