### PR TITLE
Update DNS for China

### PR DESCRIPTION
**Pull request by UjuiUjuMandan**
- Your DoH request is not correctly build according to [docs](https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/make-api-requests/dns-json/). Just use OkHttp's native DoH client.
- Old IPs in RubyHttpDns are outdated and can no longer provide `www.pixiv.net`, I replaced them with query results of `pixiv.net` (no www prefix!).
- ~~Add SNI bypass to LoginActivityWebview with shouldInterceptRequest.~~

### CODE REVIEW

**Comment by UjuiUjuMandan** [comment]
@yellowbluesky Do you use Android Studio? I don't know why Logcat is always blank...

**Comment by UjuiUjuMandan** [comment]
Let me leave WebView SNI bypass to the future...

**Comment by yellowbluesky** [comment]
I will review this in a day or two, I'm super busy at the moment

Thank you for you patience!

**Comment by yellowbluesky** [comment]
Without revealing too much, are you located in a region where the Great Firewall is in effect?

I live in Europe, so I am not able to test the functionality of your changes.

**Comment by UjuiUjuMandan** [comment]
> Without revealing too much, are you located in a region where the Great Firewall is in effect?

Yes, I am, and these changes are actually for my personal use.

**Comment by UjuiUjuMandan** [comment]
> I live in Europe, so I am not able to test the functionality of your changes.

You can not test the functionality but can test the disfunctionality before.

For DoH, use PCAPdroid to decrypt HTTPS and you’ll observe 400 bad request in response.

For SNI bypass, just switch it on and everything won’t work at all because `www.pixiv.net` can not be reached at that outdated IP.

**Review by yellowbluesky — APPROVED** [review]
Changes look good to me, and it works fine for me in Europe

**Comment by yellowbluesky** [comment]
I've merged your PR into the master.

Before I push this change to production, would you like to be credited in my app as a contributor?

**Comment by UjuiUjuMandan** [comment]
> Before I push this change to production, would you like to be credited in my app as a contributor?

I'd like to, please!

**Comment by UjuiUjuMandan** [comment]
> Before I push this change to production, would you like to be credited in my app as a contributor?

Edit: It's OK if I'm in release note, but not in app, it seems a little crowded there.

**Pull request merged**
